# 2022-03-07 19:06:04.262733: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory2022-03-07 19:06:04.262792: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.2022-03-07 19:06:05.171313: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory2022-03-07 19:06:05.171352: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)2022-03-07 19:06:05.171373: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (devel): /proc/driver/nvidia/version does not exist2022-03-07 19:06:05.171651: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMATo enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.Traceback (most recent call last):  File "/media/ivysyn/tensorflow/synthesized/all-crashes/all/AudioSummary_d4616cacc561f3b039c433f1a935685b.py", line 9, in <module>    tf.raw_ops.AudioSummary(tag=tag, tensor=tensor, sample_rate=sample_rate, max_outputs=max_outputs)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 400, in wrapper    return f(**kwargs)  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 122, in audio_summary    return audio_summary_eager_fallback(  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 149, in audio_summary_eager_fallback    sample_rate = _execute.make_float(sample_rate, "sample_rate")  File "/home/neo/.local/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 152, in make_float    raise TypeError("Expected float for argument '%s' not %s." %TypeError: Expected float for argument 'sample_rate' not <tf.Tensor: shape=(5, 3, 4), dtype=float32, numpy=array([[[1., 1., 1., 1.],        [1., 1., 1., 1.],        [1., 1., 1., 1.]],       [[1., 1., 1., 1.],        [1., 1., 1., 1.],        [1., 1., 1., 1.]],       [[1., 1., 1., 1.],        [1., 1., 1., 1.],        [1., 1., 1., 1.]],       [[1., 1., 1., 1.],        [1., 1., 1., 1.],        [1., 1., 1., 1.]],       [[1., 1., 1., 1.],        [1., 1., 1., 1.],        [1., 1., 1., 1.]]], dtype=float32)>.

# SummaryAudioOp

import tensorflow as tf

max_outputs = 3
tag = tf.constant("outer/inner", shape=[], dtype=tf.string)
tensor = tf.constant(1, shape=[5,3,4], dtype=tf.float32)
sample_rate = tf.constant(1, shape=[5,3,4], dtype=tf.float32)
tf.raw_ops.AudioSummary(tag=tag, tensor=tensor, sample_rate=sample_rate, max_outputs=max_outputs)